### PR TITLE
Bench: 2648176

### PR DESCRIPTION
**Pull request by jw1912**

### CODE REVIEW

**Comment by tissatussa** [comment]
i compiled this v0.7.0 PR 171 by git clone the newest master code, but i encounter an error "Connection Stalls" in CuteChess v1.3.1 .. after it happened, i arranged another game in CuteChess, with shorter time control, just to see if it would happen again .. and it did :

akimbo-connection-stalls1

---

akimbo-connection-stalls2

i did not save the concerning log lines which you might need to solve this problem .. but if you want i can setup new games to supply this info to you.

[ i'm on Xubuntu 22.04 ]

**Comment by jw1912** [comment]
@tissatussa thanks, please provide the log files if possible.

**Comment by tissatussa** [comment]
@jw1912 so, i should let this Akimbo version play other games ? OK, wait a while .. i will post them here, including their log files [ -- will Akimbo stall again ?? ]

**Comment by tissatussa** [comment]
bad luck .. this Akimbo version crashed again soon .. i let it play 2 games : see ZIPped log files [Akimbo-v0.7.0-PR171-two-games-log.zip](https://github.com/jw1912/akimbo/files/13401543/Akimbo-v0.7.0-PR171-two-games-log.zip)

and here are the PGNs:

```
[Event "?"]
[Site "?"]
[Date "2023.11.18"]
[Round "?"]
[White "Akimbo v0.7.0"]
[Black "El Turco v0.93"]
[Result "0-1"]
[ECO "A15"]
[GameDuration "00:01:16"]
[GameEndTime "2023-11-18T22:38:02.229 CET"]
[GameStartTime "2023-11-18T22:36:46.025 CET"]
[Opening "English, 1...Nf6 (Anglo-Indian defense)"]
[PlyCount "4"]
[Termination "stalled connection"]
[TimeControl "300+10"]

1. c4 {+0.46/24 20s} Nf6 {-0.02/9 10s} 2. d4 {+0.39/24 14s}
e6 {+0.03/9 7.0s, White's connection stalls} 0-1

[Event "?"]
[Site "?"]
[Date "2023.11.18"]
[Round "?"]
[White "Beef v0.3.6"]
[Black "Akimbo v0.7.0"]
[Result "1-0"]
[ECO "B52"]
[GameDuration "00:04:01"]
[GameEndTime "2023-11-18T22:43:24.222 CET"]
[GameStartTime "2023-11-18T22:39:23.072 CET"]
[Opening "Sicilian"]
[PlyCount "13"]
[Termination "stalled connection"]
[TimeControl "300+10"]
[Variation "Canal-Sokolsky attack, 3...Bd7"]

1. e4 {+0.24/24 8.7s} c5 {-0.26/24 20s} 2. Nf3 {+0.18/22 17s} d6 {-0.28/24 13s}
3. Bb5+ {+0.18/22 28s} Bd7 {-0.32/26 19s} 4. Bxd7+ {+0.15/21 12s}
Qxd7 {-0.22/25 8.4s} 5. Nc3 {+0.17/21 28s} Nf6 {+0.21/27 26s}
6. d4 {+0.10/21 13s} cxd4 {+0.23/26 12s}
7. Nxd4 {+0.07/23 7.8s, Black's connection stalls} 1-0
```

**Comment by jw1912** [comment]
@tissatussa that isn't a log file, please can you get the debug info (you should be able to bring up a window in cutechess that shows communication with the engine).

**Comment by jw1912** [comment]
My bad, i didn't see you provided the files

**Comment by tissatussa** [comment]
i'm not sure how this info can help you solve the problem .. however, if you want me to do some other tests, i'm willing to.

**Comment by tissatussa** [comment]
btw. as you see, i used 2 other engines to test, and let Akimbo play White and Black.

**Comment by jw1912** [comment]
@tissatussa thanks for testing and pointing this out. I've pushed a fix, it was to do with multithreading.

**Comment by tissatussa** [comment]
@jw1912 indeed the newest compiled git clone (PR 172) runs fine in CuteChess .. i tested against the same opponent engines and Akimbo did not stall its connection!

**Pull request merged**
